info:
  description: Provides course information.
  title: Course Service API
  version: 1.0.0
openapi: 3.0.0
paths:
  /course:
    get:
      responses:
        '200':
          description: A list of courses
        '500':
          description: Server error
      summary: Get all courses
  /course/{course_id}:
    get:
      parameters:
      - in: path
        name: course_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Course details
        '404':
          description: Course not found
      summary: Get course by ID
servers:
- url: http://localhost:5000
