version: '3.8'

services:
  course-logs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course-logs
    ports:
      - "5003:5003"
    depends_on:
      - mysql
    environment:
      - dbURL=mysql+mysqlconnector://is213:password@mysql:3306/course

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: courselogs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course
      MYSQL_USER: is213
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
