openapi: 3.0.0
info:
  title: Enroll Error Service API
  version: 1.0.0
  description: Validates if a user can be enrolled.

servers:
  - url: http://localhost:5004

paths:
  /validate:
    post:
      summary: Validate user before enrollment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                walletId:
                  type: string
                walletPassword:
                  type: string
                courseId:
                  type: string
                courseCost:
                  type: number
      responses:
        '200':
          description: Validation passed
        '400':
          description: Missing fields
        '402':
          description: Insufficient balance
        '409':
          description: Already enrolled
        '500':
          description: Internal error
        '502':
          description: Error calling external service
