version: '3.8'

services:
  take-course:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: take-course
    ports:
      - "5001:5001"
    environment:
      - COURSE_SERVICE_URL=http://localhost:5000
      - COURSE_LOGS_URL=http://localhost:5003
      - LESSON_SERVICE_URL=http://localhost:5005/LessonService/rest/LessonAPI
      - QUIZ_SERVICE_URL=http://localhost:8000
    networks:
      - takecourse-network

networks:
  takecourse-network:
